name: flag
description: A flag Flutter package.
version: 1.0.0
author: Luna Gao
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/res/svg1/AD.svg
    - lib/res/svg1/AE.svg
    - lib/res/svg1/AF.svg
    - lib/res/svg1/AG.svg
    - lib/res/svg1/AI.svg
    - lib/res/svg1/AL.svg
    - lib/res/svg1/AM.svg
    - lib/res/svg1/AO.svg
    - lib/res/svg1/AR.svg
    - lib/res/svg1/AS.svg
    - lib/res/svg1/AT.svg
    - lib/res/svg1/AU.svg
    - lib/res/svg1/AW.svg
    - lib/res/svg1/AX.svg
    - lib/res/svg1/AZ.svg
    - lib/res/svg1/BA.svg
    - lib/res/svg1/BB.svg
    - lib/res/svg1/BD.svg
    - lib/res/svg1/BE.svg
    - lib/res/svg1/BF.svg
    - lib/res/svg1/BG.svg
    - lib/res/svg1/BH.svg
    - lib/res/svg1/BI.svg
    - lib/res/svg1/BJ.svg
    - lib/res/svg1/BL.svg
    - lib/res/svg1/BM.svg
    - lib/res/svg1/BN.svg
    - lib/res/svg1/BO.svg
    - lib/res/svg1/BR.svg
    - lib/res/svg1/BS.svg
    - lib/res/svg1/BT.svg
    - lib/res/svg1/BV.svg
    - lib/res/svg1/BW.svg
    - lib/res/svg1/BY.svg
    - lib/res/svg1/BZ.svg
    - lib/res/svg1/CA.svg
    - lib/res/svg1/CC.svg
    - lib/res/svg1/CD.svg
    - lib/res/svg1/CF.svg
    - lib/res/svg1/CG.svg
    - lib/res/svg1/CH.svg
    - lib/res/svg1/CI.svg
    - lib/res/svg1/CK.svg
    - lib/res/svg1/CL.svg
    - lib/res/svg1/CM.svg
    - lib/res/svg1/CN.svg
    - lib/res/svg1/CO.svg
    - lib/res/svg1/CR.svg
    - lib/res/svg1/CU.svg
    - lib/res/svg1/CV.svg
    - lib/res/svg1/CW.svg
    - lib/res/svg1/CX.svg
    - lib/res/svg1/CY.svg
    - lib/res/svg1/CZ.svg
    - lib/res/svg1/DE.svg
    - lib/res/svg1/DJ.svg
    - lib/res/svg1/DK.svg
    - lib/res/svg1/DM.svg
    - lib/res/svg1/DO.svg
    - lib/res/svg1/DZ.svg
    - lib/res/svg1/EC.svg
    - lib/res/svg1/EE.svg
    - lib/res/svg1/EG.svg
    - lib/res/svg1/ER.svg
    - lib/res/svg1/ES.svg
    - lib/res/svg1/ET.svg
    - lib/res/svg1/EU.svg
    - lib/res/svg1/FI.svg
    - lib/res/svg1/FJ.svg
    - lib/res/svg1/FK.svg
    - lib/res/svg1/FM.svg
    - lib/res/svg1/FO.svg
    - lib/res/svg1/FR.svg
    - lib/res/svg1/GA.svg
    - lib/res/svg1/GB-ENG.svg
    - lib/res/svg1/GB-NIR.svg
    - lib/res/svg1/GB-SCT.svg
    - lib/res/svg1/GB-WLS.svg
    - lib/res/svg1/GB-ZET.svg
    - lib/res/svg1/GB.svg
    - lib/res/svg1/GD.svg
    - lib/res/svg1/GE.svg
    - lib/res/svg1/GF.svg
    - lib/res/svg1/GG.svg
    - lib/res/svg1/GH.svg
    - lib/res/svg1/GI.svg
    - lib/res/svg1/GL.svg
    - lib/res/svg1/GM.svg
    - lib/res/svg1/GN.svg
    - lib/res/svg1/GP.svg
    - lib/res/svg1/GQ.svg
    - lib/res/svg1/GR.svg
    - lib/res/svg1/GS.svg
    - lib/res/svg1/GT.svg
    - lib/res/svg1/GU.svg
    - lib/res/svg1/GW.svg
    - lib/res/svg1/GY.svg
    - lib/res/svg1/HK.svg
    - lib/res/svg1/HM.svg
    - lib/res/svg1/HN.svg
    - lib/res/svg1/HR.svg
    - lib/res/svg1/HT.svg
    - lib/res/svg1/HU.svg
    - lib/res/svg1/ID.svg
    - lib/res/svg1/IE.svg
    - lib/res/svg1/IL.svg
    - lib/res/svg1/IM.svg
    - lib/res/svg1/IN.svg
    - lib/res/svg1/IO.svg
    - lib/res/svg1/IQ.svg
    - lib/res/svg1/IR.svg
    - lib/res/svg1/IS.svg
    - lib/res/svg1/IT.svg
    - lib/res/svg1/JE.svg
    - lib/res/svg1/JM.svg
    - lib/res/svg1/JO.svg
    - lib/res/svg1/JP.svg
    - lib/res/svg1/KE.svg
    - lib/res/svg1/KG.svg
    - lib/res/svg1/KH.svg
    - lib/res/svg1/KI.svg
    - lib/res/svg1/KM.svg
    - lib/res/svg1/KN.svg
    - lib/res/svg1/KP.svg
    - lib/res/svg1/KR.svg
    - lib/res/svg1/KW.svg
    - lib/res/svg1/KY.svg
    - lib/res/svg1/KZ.svg
    - lib/res/svg1/LA.svg
    - lib/res/svg1/LB.svg
    - lib/res/svg1/LC.svg
    - lib/res/svg1/LGBT.svg
    - lib/res/svg1/LI.svg
    - lib/res/svg1/LK.svg
    - lib/res/svg1/LR.svg
    - lib/res/svg1/LS.svg
    - lib/res/svg1/LT.svg
    - lib/res/svg1/LU.svg
    - lib/res/svg1/LV.svg
    - lib/res/svg1/LY.svg
    - lib/res/svg1/MA.svg
    - lib/res/svg1/MC.svg
    - lib/res/svg1/MD.svg
    - lib/res/svg1/ME.svg
    - lib/res/svg1/MF.svg
    - lib/res/svg1/MG.svg
    - lib/res/svg1/MH.svg
    - lib/res/svg1/MK.svg
    - lib/res/svg1/ML.svg
    - lib/res/svg1/MM.svg
    - lib/res/svg1/MN.svg
    - lib/res/svg1/MO.svg
    - lib/res/svg1/MP.svg
    - lib/res/svg1/MQ.svg
    - lib/res/svg1/MR.svg
    - lib/res/svg1/MS.svg
    - lib/res/svg1/MT.svg
    - lib/res/svg1/MU.svg
    - lib/res/svg1/MV.svg
    - lib/res/svg1/MW.svg
    - lib/res/svg1/MX.svg
    - lib/res/svg1/MY.svg
    - lib/res/svg1/MZ.svg
    - lib/res/svg1/NA.svg
    - lib/res/svg1/NC.svg
    - lib/res/svg1/NE.svg
    - lib/res/svg1/NF.svg
    - lib/res/svg1/NG.svg
    - lib/res/svg1/NI.svg
    - lib/res/svg1/NL.svg
    - lib/res/svg1/NO.svg
    - lib/res/svg1/NP.svg
    - lib/res/svg1/NR.svg
    - lib/res/svg1/NU.svg
    - lib/res/svg1/NZ.svg
    - lib/res/svg1/OM.svg
    - lib/res/svg1/PA.svg
    - lib/res/svg1/PE.svg
    - lib/res/svg1/PF.svg
    - lib/res/svg1/PG.svg
    - lib/res/svg1/PH.svg
    - lib/res/svg1/PK.svg
    - lib/res/svg1/PL.svg
    - lib/res/svg1/PM.svg
    - lib/res/svg1/PN.svg
    - lib/res/svg1/PR.svg
    - lib/res/svg1/PS.svg
    - lib/res/svg1/PT.svg
    - lib/res/svg1/PW.svg
    - lib/res/svg1/PY.svg
    - lib/res/svg1/QA.svg
    - lib/res/svg1/RE.svg
    - lib/res/svg1/RO.svg
    - lib/res/svg1/RS.svg
    - lib/res/svg1/RU.svg
    - lib/res/svg1/RW.svg
    - lib/res/svg1/SA.svg
    - lib/res/svg1/SB.svg
    - lib/res/svg1/SC.svg
    - lib/res/svg1/SD.svg
    - lib/res/svg1/SE.svg
    - lib/res/svg1/SG.svg
    - lib/res/svg1/SH.svg
    - lib/res/svg1/SI.svg
    - lib/res/svg1/SJ.svg
    - lib/res/svg1/SK.svg
    - lib/res/svg1/SL.svg
    - lib/res/svg1/SM.svg
    - lib/res/svg1/SN.svg
    - lib/res/svg1/SO.svg
    - lib/res/svg1/SR.svg
    - lib/res/svg1/SS.svg
    - lib/res/svg1/ST.svg
    - lib/res/svg1/SV.svg
    - lib/res/svg1/SX.svg
    - lib/res/svg1/SY.svg
    - lib/res/svg1/SZ.svg
    - lib/res/svg1/TC.svg
    - lib/res/svg1/TD.svg
    - lib/res/svg1/TF.svg
    - lib/res/svg1/TG.svg
    - lib/res/svg1/TH.svg
    - lib/res/svg1/TJ.svg
    - lib/res/svg1/TK.svg
    - lib/res/svg1/TL.svg
    - lib/res/svg1/TM.svg
    - lib/res/svg1/TN.svg
    - lib/res/svg1/TO.svg
    - lib/res/svg1/TR.svg
    - lib/res/svg1/TT.svg
    - lib/res/svg1/TV.svg
    - lib/res/svg1/TW.svg
    - lib/res/svg1/TZ.svg
    - lib/res/svg1/UA.svg
    - lib/res/svg1/UG.svg
    - lib/res/svg1/UM.svg
    - lib/res/svg1/US-CA.svg
    - lib/res/svg1/US.svg
    - lib/res/svg1/UY.svg
    - lib/res/svg1/UZ.svg
    - lib/res/svg1/VA.svg
    - lib/res/svg1/VC.svg
    - lib/res/svg1/VE.svg
    - lib/res/svg1/VG.svg
    - lib/res/svg1/VI.svg
    - lib/res/svg1/VN.svg
    - lib/res/svg1/VU.svg
    - lib/res/svg1/WF.svg
    - lib/res/svg1/WS.svg
    - lib/res/svg1/XK.svg
    - lib/res/svg1/YE.svg
    - lib/res/svg1/YT.svg
    - lib/res/svg1/ZA.svg
    - lib/res/svg1/ZM.svg
    - lib/res/svg1/ZW.svg
    - lib/res/svg2/ad.svg
    - lib/res/svg2/ae.svg
    - lib/res/svg2/af.svg
    - lib/res/svg2/ag.svg
    - lib/res/svg2/ai.svg
    - lib/res/svg2/al.svg
    - lib/res/svg2/am.svg
    - lib/res/svg2/an.svg
    - lib/res/svg2/ao.svg
    - lib/res/svg2/aq.svg
    - lib/res/svg2/ar.svg
    - lib/res/svg2/as.svg
    - lib/res/svg2/at.svg
    - lib/res/svg2/au.svg
    - lib/res/svg2/aw.svg
    - lib/res/svg2/ax.svg
    - lib/res/svg2/az.svg
    - lib/res/svg2/ba.svg
    - lib/res/svg2/bb.svg
    - lib/res/svg2/bd.svg
    - lib/res/svg2/be.svg
    - lib/res/svg2/bf.svg
    - lib/res/svg2/bg.svg
    - lib/res/svg2/bh.svg
    - lib/res/svg2/bi.svg
    - lib/res/svg2/bj.svg
    - lib/res/svg2/bl.svg
    - lib/res/svg2/bm.svg
    - lib/res/svg2/bn.svg
    - lib/res/svg2/bo.svg
    - lib/res/svg2/bq.svg
    - lib/res/svg2/br.svg
    - lib/res/svg2/bs.svg
    - lib/res/svg2/bt.svg
    - lib/res/svg2/bv.svg
    - lib/res/svg2/bw.svg
    - lib/res/svg2/by.svg
    - lib/res/svg2/bz.svg
    - lib/res/svg2/ca.svg
    - lib/res/svg2/cc.svg
    - lib/res/svg2/cd.svg
    - lib/res/svg2/cf.svg
    - lib/res/svg2/cg.svg
    - lib/res/svg2/ch.svg
    - lib/res/svg2/ci.svg
    - lib/res/svg2/ck.svg
    - lib/res/svg2/cl.svg
    - lib/res/svg2/cm.svg
    - lib/res/svg2/cn.svg
    - lib/res/svg2/co.svg
    - lib/res/svg2/cr.svg
    - lib/res/svg2/cu.svg
    - lib/res/svg2/cv.svg
    - lib/res/svg2/cw.svg
    - lib/res/svg2/cx.svg
    - lib/res/svg2/cy.svg
    - lib/res/svg2/cz.svg
    - lib/res/svg2/de.svg
    - lib/res/svg2/dj.svg
    - lib/res/svg2/dk.svg
    - lib/res/svg2/dm.svg
    - lib/res/svg2/do.svg
    - lib/res/svg2/dz.svg
    - lib/res/svg2/ec.svg
    - lib/res/svg2/ee.svg
    - lib/res/svg2/eg.svg
    - lib/res/svg2/eh.svg
    - lib/res/svg2/er.svg
    - lib/res/svg2/es.svg
    - lib/res/svg2/et.svg
    - lib/res/svg2/eu.svg
    - lib/res/svg2/fi.svg
    - lib/res/svg2/fj.svg
    - lib/res/svg2/fk.svg
    - lib/res/svg2/fm.svg
    - lib/res/svg2/fo.svg
    - lib/res/svg2/fr.svg
    - lib/res/svg2/ga.svg
    - lib/res/svg2/gb-eng.svg
    - lib/res/svg2/gb-nir.svg
    - lib/res/svg2/gb-sct.svg
    - lib/res/svg2/gb-wls.svg
    - lib/res/svg2/gb.svg
    - lib/res/svg2/gd.svg
    - lib/res/svg2/ge.svg
    - lib/res/svg2/gf.svg
    - lib/res/svg2/gg.svg
    - lib/res/svg2/gh.svg
    - lib/res/svg2/gi.svg
    - lib/res/svg2/gl.svg
    - lib/res/svg2/gm.svg
    - lib/res/svg2/gn.svg
    - lib/res/svg2/gp.svg
    - lib/res/svg2/gq.svg
    - lib/res/svg2/gr.svg
    - lib/res/svg2/gs.svg
    - lib/res/svg2/gt.svg
    - lib/res/svg2/gu.svg
    - lib/res/svg2/gw.svg
    - lib/res/svg2/gy.svg
    - lib/res/svg2/hk.svg
    - lib/res/svg2/hm.svg
    - lib/res/svg2/hn.svg
    - lib/res/svg2/hr.svg
    - lib/res/svg2/ht.svg
    - lib/res/svg2/hu.svg
    - lib/res/svg2/id.svg
    - lib/res/svg2/ie.svg
    - lib/res/svg2/il.svg
    - lib/res/svg2/im.svg
    - lib/res/svg2/in.svg
    - lib/res/svg2/io.svg
    - lib/res/svg2/iq.svg
    - lib/res/svg2/ir.svg
    - lib/res/svg2/is.svg
    - lib/res/svg2/it.svg
    - lib/res/svg2/je.svg
    - lib/res/svg2/jm.svg
    - lib/res/svg2/jo.svg
    - lib/res/svg2/jp.svg
    - lib/res/svg2/ke.svg
    - lib/res/svg2/kg.svg
    - lib/res/svg2/kh.svg
    - lib/res/svg2/ki.svg
    - lib/res/svg2/km.svg
    - lib/res/svg2/kn.svg
    - lib/res/svg2/kp.svg
    - lib/res/svg2/kr.svg
    - lib/res/svg2/kw.svg
    - lib/res/svg2/ky.svg
    - lib/res/svg2/kz.svg
    - lib/res/svg2/la.svg
    - lib/res/svg2/lb.svg
    - lib/res/svg2/lc.svg
    - lib/res/svg2/li.svg
    - lib/res/svg2/lk.svg
    - lib/res/svg2/lr.svg
    - lib/res/svg2/ls.svg
    - lib/res/svg2/lt.svg
    - lib/res/svg2/lu.svg
    - lib/res/svg2/lv.svg
    - lib/res/svg2/ly.svg
    - lib/res/svg2/ma.svg
    - lib/res/svg2/mc.svg
    - lib/res/svg2/md.svg
    - lib/res/svg2/me.svg
    - lib/res/svg2/mf.svg
    - lib/res/svg2/mg.svg
    - lib/res/svg2/mh.svg
    - lib/res/svg2/mk.svg
    - lib/res/svg2/ml.svg
    - lib/res/svg2/mm.svg
    - lib/res/svg2/mn.svg
    - lib/res/svg2/mo.svg
    - lib/res/svg2/mp.svg
    - lib/res/svg2/mq.svg
    - lib/res/svg2/mr.svg
    - lib/res/svg2/ms.svg
    - lib/res/svg2/mt.svg
    - lib/res/svg2/mu.svg
    - lib/res/svg2/mv.svg
    - lib/res/svg2/mw.svg
    - lib/res/svg2/mx.svg
    - lib/res/svg2/my.svg
    - lib/res/svg2/mz.svg
    - lib/res/svg2/na.svg
    - lib/res/svg2/nc.svg
    - lib/res/svg2/ne.svg
    - lib/res/svg2/nf.svg
    - lib/res/svg2/ng.svg
    - lib/res/svg2/ni.svg
    - lib/res/svg2/nl.svg
    - lib/res/svg2/no.svg
    - lib/res/svg2/np.svg
    - lib/res/svg2/nr.svg
    - lib/res/svg2/nu.svg
    - lib/res/svg2/nz.svg
    - lib/res/svg2/om.svg
    - lib/res/svg2/pa.svg
    - lib/res/svg2/pe.svg
    - lib/res/svg2/pf.svg
    - lib/res/svg2/pg.svg
    - lib/res/svg2/ph.svg
    - lib/res/svg2/pk.svg
    - lib/res/svg2/pl.svg
    - lib/res/svg2/pm.svg
    - lib/res/svg2/pn.svg
    - lib/res/svg2/pr.svg
    - lib/res/svg2/ps.svg
    - lib/res/svg2/pt.svg
    - lib/res/svg2/pw.svg
    - lib/res/svg2/py.svg
    - lib/res/svg2/qa.svg
    - lib/res/svg2/re.svg
    - lib/res/svg2/ro.svg
    - lib/res/svg2/rs.svg
    - lib/res/svg2/ru.svg
    - lib/res/svg2/rw.svg
    - lib/res/svg2/sa.svg
    - lib/res/svg2/sb.svg
    - lib/res/svg2/sc.svg
    - lib/res/svg2/sd.svg
    - lib/res/svg2/se.svg
    - lib/res/svg2/sg.svg
    - lib/res/svg2/sh.svg
    - lib/res/svg2/si.svg
    - lib/res/svg2/sj.svg
    - lib/res/svg2/sk.svg
    - lib/res/svg2/sl.svg
    - lib/res/svg2/sm.svg
    - lib/res/svg2/sn.svg
    - lib/res/svg2/so.svg
    - lib/res/svg2/sr.svg
    - lib/res/svg2/ss.svg
    - lib/res/svg2/st.svg
    - lib/res/svg2/sv.svg
    - lib/res/svg2/sx.svg
    - lib/res/svg2/sy.svg
    - lib/res/svg2/sz.svg
    - lib/res/svg2/tc.svg
    - lib/res/svg2/td.svg
    - lib/res/svg2/tf.svg
    - lib/res/svg2/tg.svg
    - lib/res/svg2/th.svg
    - lib/res/svg2/tj.svg
    - lib/res/svg2/tk.svg
    - lib/res/svg2/tl.svg
    - lib/res/svg2/tm.svg
    - lib/res/svg2/tn.svg
    - lib/res/svg2/to.svg
    - lib/res/svg2/tr.svg
    - lib/res/svg2/tt.svg
    - lib/res/svg2/tv.svg
    - lib/res/svg2/tw.svg
    - lib/res/svg2/tz.svg
    - lib/res/svg2/ua.svg
    - lib/res/svg2/ug.svg
    - lib/res/svg2/um.svg
    - lib/res/svg2/us.svg
    - lib/res/svg2/uy.svg
    - lib/res/svg2/uz.svg
    - lib/res/svg2/va.svg
    - lib/res/svg2/vc.svg
    - lib/res/svg2/ve.svg
    - lib/res/svg2/vg.svg
    - lib/res/svg2/vi.svg
    - lib/res/svg2/vn.svg
    - lib/res/svg2/vu.svg
    - lib/res/svg2/wf.svg
    - lib/res/svg2/ws.svg
    - lib/res/svg2/xk.svg
    - lib/res/svg2/ye.svg
    - lib/res/svg2/yt.svg
    - lib/res/svg2/za.svg
    - lib/res/svg2/zm.svg
    - lib/res/svg2/zw.svg
