name: flag
description: A flag Flutter package. Use for showing flags. All flags came from https://www.un.org/en/member-states/index.html . 
version: 3.0.4
homepage: https://github.com/LunaGao/flag_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - res/flag/
