name: flag
description: A flag Flutter package. Use for showing flags. All flags came from https://github.com/lipis/flag-icons/releases/tag/v4.1.4 .
version: 7.0.1
homepage: https://github.com/LunaGao/flag_flutter

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.6
  enum_to_string: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - res/1x1/
    - res/4x3/
